import {
  // Generic / shared
  LayoutDashboard,
  ShoppingCart,
  Receipt,
  Package,
  Warehouse,
  Users,
  UserCheck,
  DollarSign,
  Truck,
  Car,
  Store,
  FileText,
  Building2,
  Plug,
  Wrench,
  CalendarDays,
  Trash2,
  KeyRound,
  Undo2,
  CreditCard,
  ClipboardList,
  Tag,
  Zap,
  MessageSquare,
  Bot,
  TrendingUp,
  BarChart3,
  ShoppingBag,
  Gift,
  Clock,
  ArrowRightLeft,
  FileBox,
  ScrollText,
  Mail,
  // Furniture-themed
  Sofa,
  Bed,
  Armchair,
  Lamp,
  Hammer,
  Ruler,
  Boxes,
  Home,
  Sparkles,
  Code2,
  Puzzle,
  GraduationCap,
  type LucideIcon,
} from 'lucide-react';
import { WhatsAppIcon } from '@/components/icons/WhatsAppIcon';

export type MenuTheme = 'party' | 'furniture';

/**
 * Icon overrides per theme. Keys are stable identifiers used by the sidebar.
 * The 'party' theme keeps the original icons (no override needed for most),
 * while 'furniture' swaps several for furniture-themed equivalents.
 */
const ICONS: Record<MenuTheme, Record<string, LucideIcon>> = {
  party: {
    dashboard: LayoutDashboard,
    pdv: ShoppingCart,
    pdvRapido: Zap,
    sales: Receipt,
    cash: DollarSign,
    // groups
    catalog: Package,
    commercial: ScrollText,
    team: UserCheck,
    logistics: Truck,
    chat: WhatsAppIcon as unknown as LucideIcon,
    fiscal: FileText,
    integrations: Plug,
    settings: Store,
    // catalog items
    products: Package,
    categories: Tag,
    inventory: Warehouse,
    transfers: ArrowRightLeft,
    labels: Tag,
    expiration: Clock,
    customers: Users,
    suppliers: Building2,
    crediario: CreditCard,
    storeCredits: Gift,
    // commercial
    quotes: ScrollText,
    purchaseOrders: FileBox,
    replenishment: ShoppingCart,
    // team
    sellers: UserCheck,
    commissionTiers: TrendingUp,
    finance: DollarSign,
    myCommissions: DollarSign,
    // logistics
    drivers: Car,
    deliveries: Truck,
    assemblers: Wrench,
    assemblies: CalendarDays,
    // chat
    chatList: WhatsAppIcon as unknown as LucideIcon,
    chatbot: Bot,
    // fiscal
    fiscalSettings: FileText,
    fiscalCounter: BarChart3,
    fiscalEntries: FileText,
    fiscalReturns: Undo2,
    supplierReturns: Undo2,
    // settings
    subscription: CreditCard,
    stores: Store,
    ecommerce: ShoppingBag,
    activityLogs: ClipboardList,
    pin: KeyRound,
    reset: Trash2,
    businessType: Store,
    integrationsItem: Plug,
    aiSimulation: Sparkles,
    marketing: Mail,
    emailCampaigns: Mail,
    picking: Boxes,
    customerReturns: Undo2,
    salesGoals: TrendingUp,
    reactivation: MessageSquare,
    developers: Code2,
    apiConnectors: Puzzle,
    training: GraduationCap,
  },
  furniture: {
    dashboard: Home,
    pdv: ShoppingCart,
    pdvRapido: Zap,
    sales: Receipt,
    cash: DollarSign,
    // groups
    catalog: Sofa,
    commercial: ScrollText,
    team: UserCheck,
    logistics: Truck,
    chat: WhatsAppIcon as unknown as LucideIcon,
    fiscal: FileText,
    integrations: Plug,
    settings: Store,
    // catalog items — furniture themed
    products: Sofa,
    categories: Armchair,
    inventory: Boxes,
    transfers: ArrowRightLeft,
    labels: Tag,
    expiration: Clock,
    customers: Users,
    suppliers: Building2,
    crediario: CreditCard,
    storeCredits: Gift,
    // commercial
    quotes: ScrollText,
    purchaseOrders: FileBox,
    replenishment: ShoppingCart,
    // team
    sellers: UserCheck,
    commissionTiers: TrendingUp,
    finance: DollarSign,
    myCommissions: DollarSign,
    // logistics — furniture themed (montagem = key activity)
    drivers: Car,
    deliveries: Truck,
    assemblers: Hammer,
    assemblies: Ruler,
    // chat
    chatList: WhatsAppIcon as unknown as LucideIcon,
    chatbot: Bot,
    // fiscal
    fiscalSettings: FileText,
    fiscalCounter: BarChart3,
    fiscalEntries: FileText,
    fiscalReturns: Undo2,
    supplierReturns: Undo2,
    // settings
    subscription: CreditCard,
    stores: Store,
    ecommerce: ShoppingBag,
    activityLogs: ClipboardList,
    pin: KeyRound,
    reset: Trash2,
    businessType: Store,
    integrationsItem: Plug,
    aiSimulation: Sparkles,
    marketing: Mail,
    emailCampaigns: Mail,
    picking: Boxes,
    customerReturns: Undo2,
    salesGoals: TrendingUp,
    reactivation: MessageSquare,
    developers: Code2,
    apiConnectors: Puzzle,
    training: GraduationCap,
    // unique decorative slot (furniture vibes)
    bedExample: Bed,
    lampExample: Lamp,
  },
};

export function getMenuIcons(theme: MenuTheme | undefined | null): Record<string, LucideIcon> {
  return ICONS[theme === 'furniture' ? 'furniture' : 'party'];
}

export const MENU_THEME_OPTIONS: { value: MenuTheme; label: string; description: string }[] = [
  { value: 'party', label: 'Loja de Festas', description: 'Ícones padrão (caixa, sacola, presente).' },
  { value: 'furniture', label: 'Loja de Móveis', description: 'Ícones temáticos (sofá, poltrona, cama, martelo, régua).' },
];
