ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS origem_icms text DEFAULT '0',
  ADD COLUMN IF NOT EXISTS cst_icms text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS csosn text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cst_pis text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cst_cofins text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cst_ipi text DEFAULT NULL;